#!/bin/sh
set -e

export PGPASSWORD="{{cfg.db.password}}"

PSQL_ARGS="-w -h {{bind.datastore.first.sys.ip}} -p {{bind.datastore.first.cfg.port}} -U {{cfg.db.user}} {{cfg.db.database}}"
# shellcheck disable=SC2086
# Create the DB or check that it exists
createdb $PSQL_ARGS || psql -c ";" $PSQL_ARGS
